# Generated by Django 5.2.7 on 2025-10-30 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_added", models.DateField(default=django.utils.timezone.now)),
                ("tool_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("warranty_date", models.DateField(blank=True, null=True)),
                ("assigned_user", models.CharField(blank=True, max_length=255, null=True)),
                ("assigned_by", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, null=True, upload_to="assets_tools/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset/Tool",
                "verbose_name_plural": "Assets/Tools",
                "ordering": ["-date_added"],
            },
        ),
    ]
