# Generated by Django 5.2.7 on 2025-10-30 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("change_type", models.CharField(choices=[("ASSIGNED", "Assigned"), ("RETURNED", "Returned")], max_length=20)),
                ("assigned_to", models.CharField(blank=True, max_length=255, null=True)),
                ("previous_user", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("undone", models.BooleanField(default=False)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="app_core.assettool")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
