# Generated by Django 5.2.7 on 2025-10-30 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0002_assethistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "previous_user",
                    models.CharField(blank=True, help_text="The user previously assigned to this asset.", max_length=255, null=True),
                ),
                ("assigned_to", models.CharField(blank=True, help_text="The new user assigned to this asset.", max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, help_text="Any notes about the change.", null=True)),
                (
                    "transaction_date",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="The date and time this update was recorded."),
                ),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="app_core.assettool")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The system user who performed the update.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
