# Generated by Django 5.2.7 on 2025-11-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0003_assetupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettool",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
