# Generated by Django 5.2.7 on 2025-11-03 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0004_assettool_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assettool",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
