# Generated by Django 5.2.7 on 2025-11-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0005_alter_assettool_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetupdate",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True, help_text="The date and time this update was recorded."),
        ),
    ]
