# Generated by Django 5.2.7 on 2025-11-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0006_alter_assetupdate_transaction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_title", models.CharField(max_length=255)),
                ("po_no", models.CharField(max_length=50, verbose_name="P.O. No.")),
                ("remarks", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
