# Generated by Django 5.2.7 on 2025-11-05 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0007_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
