# Generated by Django 5.2.7 on 2025-11-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0008_project_created_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("project_title", "po_no")},
        ),
    ]
