# Generated by Django 5.2.7 on 2025-11-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0009_alter_project_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDR",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dr_number", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="uploaded_drs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
