# Generated by Django 5.2.7 on 2025-11-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0010_uploadeddr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddr",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="uploadeddr",
            name="po_number",
            field=models.CharField(default="TEMP-PO", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadeddr",
            name="uploaded_date",
            field=models.DateField(default="2025-11-06"),
            preserve_default=False,
        ),
    ]
