# Generated by Django 5.2.7 on 2025-10-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_item_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="item_id",
        ),
    ]
