# Generated by Django 5.2.7 on 2025-10-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_total_stock_itemupdate_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='allocated_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
