# Generated by Django 5.2.7 on 2025-10-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_item_allocated_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemserial",
            name="date_added",
        ),
    ]
