# Generated by Django 5.2.7 on 2025-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_itemserial_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemupdate',
            name='stock_after_transaction',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
