# Generated by Django 5.2.7 on 2025-10-23 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_itemupdate_stock_after_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="date_last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
