# Generated by Django 5.2.7 on 2025-10-23 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_item_date_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemupdate",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
