# Generated by Django 5.2.7 on 2025-10-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='action_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('undo', 'Undo Transaction'), ('add', 'New Item Added')], max_length=20),
        ),
    ]
