# Generated by Django 5.2.7 on 2025-10-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_transactionhistory_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemupdate',
            name='undone',
            field=models.BooleanField(default=False),
        ),
    ]
