# Generated by Django 5.2.7 on 2025-10-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_itemupdate_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemupdate',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
