# Generated by Django 5.2.7 on 2025-10-29 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_alter_itemupdate_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="allocated_quantity",
        ),
        migrations.RemoveField(
            model_name="item",
            name="part_no",
        ),
        migrations.RemoveField(
            model_name="item",
            name="total_stock",
        ),
        migrations.RemoveField(
            model_name="item",
            name="unit_of_quantity",
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
