# Generated by Django 5.2.7 on 2025-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_remove_item_allocated_quantity_remove_item_part_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="allocated_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="part_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="total_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="unit_of_quantity",
            field=models.CharField(choices=[("pcs", "Pieces"), ("rolls", "Rolls"), ("meters", "Meters")], default="pcs", max_length=20),
        ),
    ]
