# Generated by Django 5.2.7 on 2025-11-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_item_allocated_quantity_item_part_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="unit_of_quantity",
            field=models.CharField(
                choices=[("pcs", "Pieces"), ("rolls", "Rolls"), ("meters", "Meters"), ("gallons", "Gallons")], default="pcs", max_length=20
            ),
        ),
    ]
