# Generated by Django 5.2.7 on 2025-11-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_alter_item_unit_of_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="unit_of_quantity",
            field=models.CharField(
                choices=[
                    ("pcs", "Pieces"),
                    ("rolls", "Rolls"),
                    ("meters", "Meters"),
                    ("gallons", "Gallons"),
                    ("litters", "Litters"),
                    ("bottles", "Bottles"),
                    ("cans", "Cans"),
                ],
                default="pcs",
                max_length=20,
            ),
        ),
    ]
